name: 'On'

on:
  push:
    branches:
      - staging
    paths:
      - src/**

jobs:
  changes:
    name: Changes
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      packages: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: main
          filters: |
            hoge: src/hoge/**
            piyo: src/piyo/**
            tyun: src/tyun/**

  sample:
    name: Sample
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: ${{ fromJSON(needs.changes.outputs.packages) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set params
        run: |
          num=$(yq .${{ matrix.packages }}.num .github/params.yaml)
          echo ${num}
          echo "NUM=${num}" >> "$GITHUB_ENV"

      - run: |
          echo ${{ env.NUM }}
          echo $NUM
